In [34]:
import numpy as np
from numpy import *


In [35]:
a=np.array([[0,1,2,3,4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34]])
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [36]:
a[0,0]

0

In [37]:
a[-1]

array([30, 31, 32, 33, 34])

In [38]:
a[1:3,1:4]

array([[11, 12, 13],
       [21, 22, 23]])

In [39]:
i=np.array([0,1,2,1])
j=np.array([1,2,3,4])

In [40]:
a[i,j]

array([ 1, 12, 23, 14])

In [41]:
a[a<13]

array([ 0,  1,  2,  3,  4, 10, 11, 12])

In [42]:
b1=np.array([True,False,True,False])

In [43]:
a[b1,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [44]:
b2=np.array([True,False,True,False,True])
a[b1,:]


array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [45]:
a=np.arange(12)
a=a.reshape(3,2,2)
print (a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [46]:
a=a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [47]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# abs()

In [48]:
abs(-1)

1

In [49]:
abs(array([-1.2,1.2]))

array([1.2, 1.2])

In [50]:
abs(1.2+1j)

1.5620499351813308

# accumulate()

it is used to compute the cummulative sum of elements in a input array

In [51]:
from numpy import*
add.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  3.,  6., 10.])

In [52]:
multiply.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  2.,  6., 24.])

In [53]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [54]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])