In [1]:
import numpy as np

# The bascis

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#get dimensiion
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#get shape
b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int32')

In [9]:
#get size
a.itemsize

4

In [10]:
#total size
a.nbytes

12

# Acessing/changing specific elements,rowa and columns

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
#get a specific elemtn [r,c]
a[1,5]

13

In [15]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#get a specific column
a[:,2]

array([ 3, 10])

In [17]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [21]:
a[1,5]=20
a

a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [30]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [31]:
b[:,1,:]=[[9,9],[8,8]]

ValueError: could not broadcast input array from shape (2,2) into shape (1,2)

# initialise different types of array

In [33]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
# all 1s matrix
np.ones((4,2,2),dtype='int')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [37]:
# any other number
np.full((2,2),55,dtype=float)

array([[55., 55.],
       [55., 55.]])

In [40]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
#random decimal numbers
np.random.rand(4,3)

array([[0.56128935, 0.78035824, 0.99464108],
       [0.85086212, 0.96688585, 0.37519391],
       [0.79035221, 0.09194889, 0.78866055],
       [0.69808218, 0.75917794, 0.20183777]])

In [47]:
#random integer values
np.random.randint(4,7,size =(3,3))

array([[4, 5, 4],
       [4, 6, 5],
       [4, 4, 6]])

In [48]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
arr=np.array([[1,2,3]]) # repeat an arrY
r1=np.repeat(arr,3,axis=0) # or axis=1 vertical 
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
output=np.ones((5,5))
print(output)


z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# be careful when copying arrays

In [61]:
a=np.array([1,2,3])
b=a
b[0]=100
a

array([100,   2,   3])

In [64]:
b=a.copy
a

array([100,   2,   3])

# Mathematics

In [65]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [66]:
a+2

array([3, 4, 5, 6])

In [67]:
a-2

array([-1,  0,  1,  2])

In [68]:
a*2

array([2, 4, 6, 8])

In [69]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [70]:
a**2

array([ 1,  4,  9, 16])

In [71]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [72]:
# take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [73]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear algebra

In [76]:
a=np.full((2,3),2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [78]:
b=np.full((3,2),1)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [80]:
np.matmul(a,b)# matrix multiply

array([[6, 6],
       [6, 6]])

In [81]:
c=np.identity(3)
np.linalg.det(c)

1.0

# statics

In [82]:
stats=np.array([[1,2,3,],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(stats)

1

In [86]:
np.max(stats,axis=1)

array([3, 6])

In [87]:
np.sum(stats)

21

# reorganizing arrays

In [88]:
before=np.array([[[1,2,3,4],[5,6,7,8]]])
before

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [90]:
after=before.reshape((2,3))
after

ValueError: cannot reshape array of size 8 into shape (2,3)

In [91]:
# vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])


np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
# horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))


np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Boolean masking and Advanced indexing

In [93]:
stats>50

array([[False, False, False],
       [False, False, False]])

In [94]:
stats[stats>50]




array([], dtype=int32)

In [96]:
#you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [97]:
np.any(stats>5,axis=0)

array([False, False,  True])

In [98]:
np.all(stats>4,axis=1)

array([False, False])

In [99]:
(stats>6 )&(stats<2)

array([[False, False, False],
       [False, False, False]])